/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconFa6Solid:cartShopping': typeof import('~icons/fa6-solid/cart-shopping')['default']
    'IconFa6Solid:circleUser': typeof import('~icons/fa6-solid/circle-user')['default']
    'IconFa6Solid:magnifyingGlass': typeof import('~icons/fa6-solid/magnifying-glass')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
