/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		'IconBi:exclamationCircleFill': (typeof import('~icons/bi/exclamation-circle-fill'))['default']
		'IconCarbon:twoFactorAuthentication': (typeof import('~icons/carbon/two-factor-authentication'))['default']
		'IconClarity:timesCircleSolid': (typeof import('~icons/clarity/times-circle-solid'))['default']
		'IconClarity:timesLine': (typeof import('~icons/clarity/times-line'))['default']
		'IconEntypo:arrowLeft': (typeof import('~icons/entypo/arrow-left'))['default']
		'IconEntypo:circleWithCross': (typeof import('~icons/entypo/circle-with-cross'))['default']
		'IconFa6Solid:arrowLeft': (typeof import('~icons/fa6-solid/arrow-left'))['default']
		'IconFa6Solid:cartShopping': (typeof import('~icons/fa6-solid/cart-shopping'))['default']
		'IconFa6Solid:circleCheck': (typeof import('~icons/fa6-solid/circle-check'))['default']
		'IconFa6Solid:circleQuestion': (typeof import('~icons/fa6-solid/circle-question'))['default']
		'IconFa6Solid:circleUser': (typeof import('~icons/fa6-solid/circle-user'))['default']
		'IconFa6Solid:clockRotateLeft': (typeof import('~icons/fa6-solid/clock-rotate-left'))['default']
		'IconFa6Solid:eye': (typeof import('~icons/fa6-solid/eye'))['default']
		'IconFa6Solid:eyeSlash': (typeof import('~icons/fa6-solid/eye-slash'))['default']
		'IconFa6Solid:magnifyingGlass': (typeof import('~icons/fa6-solid/magnifying-glass'))['default']
		'IconFa6Solid:pencil': (typeof import('~icons/fa6-solid/pencil'))['default']
		'IconFa6Solid:trash': (typeof import('~icons/fa6-solid/trash'))['default']
		'IconFaSolid:angleLeft': (typeof import('~icons/fa-solid/angle-left'))['default']
		'IconFaSolid:angleRight': (typeof import('~icons/fa-solid/angle-right'))['default']
		'IconFaSolid:check': (typeof import('~icons/fa-solid/check'))['default']
		'IconFaSolid:ellipsisV': (typeof import('~icons/fa-solid/ellipsis-v'))['default']
		'IconFaSolid:minus': (typeof import('~icons/fa-solid/minus'))['default']
		'IconFaSolid:pen': (typeof import('~icons/fa-solid/pen'))['default']
		'IconFaSolid:plus': (typeof import('~icons/fa-solid/plus'))['default']
		'IconFaSolid:sort': (typeof import('~icons/fa-solid/sort'))['default']
		'IconFaSolid:trash': (typeof import('~icons/fa-solid/trash'))['default']
		'IconFluent:doorArrowRight28Regular': (typeof import('~icons/fluent/door-arrow-right28-regular'))['default']
		'IconIc:baselineContentCopy': (typeof import('~icons/ic/baseline-content-copy'))['default']
		'IconLa:language': (typeof import('~icons/la/language'))['default']
		'IconMdi:checkCircle': (typeof import('~icons/mdi/check-circle'))['default']
		'IconMdi:githubFace': (typeof import('~icons/mdi/github-face'))['default']
		'IconMdi:heart': (typeof import('~icons/mdi/heart'))['default']
		'IconMdi:heartOutline': (typeof import('~icons/mdi/heart-outline'))['default']
		'IconMdi:packageVariantClosed': (typeof import('~icons/mdi/package-variant-closed'))['default']
		'IconMdi:star': (typeof import('~icons/mdi/star'))['default']
		'IconMdi:starOutline': (typeof import('~icons/mdi/star-outline'))['default']
		'IconUil:angleDown': (typeof import('~icons/uil/angle-down'))['default']
		'IconUil:apps': (typeof import('~icons/uil/apps'))['default']
		'IconUil:bars': (typeof import('~icons/uil/bars'))['default']
		'IconUil:times': (typeof import('~icons/uil/times'))['default']
		RouterLink: (typeof import('vue-router'))['RouterLink']
		RouterView: (typeof import('vue-router'))['RouterView']
	}
}
