import eslintPluginBetterTailwindcss from 'eslint-plugin-better-tailwindcss'
import vitest from '@vitest/eslint-plugin'
// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'
import { globalIgnores } from 'eslint/config'

/**
 * `no-restricted-syntax` selectors, kept as values because the rule is
 * set by more than one config object below. ESLint does not concatenate
 * a rule's options across matching objects — the LATER object's options
 * replace the earlier ones outright ("Configure Rules": the rule
 * configuration is merged with the later object taking precedence) — so
 * an object scoped to `app/components/**` has to repeat every app-wide
 * selector, or it silently switches the app-wide ones off there.
 */
const APP_FETCHER_SELECTORS = [
  {
    selector: 'CallExpression[callee.name=/^(\\$fetch|useFetch|useLazyFetch|useRequestFetch)$/]',
    message: 'Use $api / useApi / useLazyApi / useRequestApi — they send the page locale. See app/utils/api.ts.',
  },
  {
    selector: 'MemberExpression[object.name="$fetch"]',
    message: 'Use $api — it sends the page locale. See app/utils/api.ts.',
  },
]

/**
 * `usePageConfig()` must be awaited. Nuxt registers useFetch's promise
 * with `onServerPrefetch` and lets setup continue, so an un-awaited call
 * leaves `data`/`error` null for the rest of setup on the server — which
 * made every layout-driven page (/about, /vision, custom [slug] pages)
 * throw its own 404 on every cold server render.
 */
const PAGE_CONFIG_AWAITED = {
  selector: ':not(AwaitExpression) > CallExpression[callee.name="usePageConfig"]',
  message: 'Await usePageConfig() — un-awaited, its data is still null for the rest of setup on the server, and the page 404s.',
}

/**
 * Page macros belong in `app/pages/`: Nuxt extracts `definePageMeta` and
 * `defineRouteRules` only from page files, so in a component (a page
 * BODY under `Storefront/` or `variants/`) they are inert and the route
 * silently loses its middleware or robots rule.
 */
const NO_PAGE_MACROS = {
  selector: 'CallExpression[callee.name=/^(definePageMeta|defineRouteRules)$/]',
  message: 'Page macros only work in app/pages/ — move this to the page shell that mounts the component.',
}

/**
 * A promise returned from a `try` without `await` settles after the try
 * has exited, so its rejection never reaches the `catch` — in a server
 * route, `handleError`, which is what reports a drifted response loudly.
 * Three shipping routes returned `parseDataAs(...)` that way: a contract
 * break reached the client as a 422 and was never logged. The callees
 * named here are the async ones routes return from their `try` —
 * `parseDataAs`, `$fetch` / `$fetch.raw`, `useBackendFetch()(...)` and
 * its `backendFetch` alias — bare or behind `as` / `!`.
 * typescript-eslint's `return-await` would cover any promise, but needs
 * typed linting, which this config does not run.
 */
const ASYNC_CALLEE = ':matches([callee.name=/^(parseDataAs|\\$fetch|backendFetch)$/], [callee.object.name="$fetch"], [callee.callee.name="useBackendFetch"])'
const RETURN_AWAITED_IN_TRY = ['', 'TSAsExpression > ', 'TSNonNullExpression > '].map(wrapper => ({
  selector: `TryStatement > BlockStatement ReturnStatement > ${wrapper}CallExpression${ASYNC_CALLEE}`,
  message: 'Return `await` inside try: an un-awaited promise rejects after the try exits, so the catch (handleError) never sees the failure.',
}))

export default withNuxt(
  globalIgnores([
    // Only ignore the raw schema files at the project root, NOT the
    // generated TS/Zod sources in ``shared/openapi/`` — otherwise the
    // openapi-ts ESLint post-processor fails with "all matching files
    // are ignored" and the codegen crashes mid-run.
    'openapi/**',
    '**/.nuxt/**',
    '**/.output/**',
    '**/dist/**',
    '**/build/**',
    '**/node_modules/**',
    '**/.pnpm-store/**',
    '**/.cache/**',
    '**/.eslintcache',
    '**/coverage/**',
    '**/*.log',
    '**/*.md',
    '**/logs/**',
    '**/skills/**',
  ]),
  {
    plugins: {
      'better-tailwindcss': eslintPluginBetterTailwindcss,
    },
  },
  {
    // Generated by @hey-api/openapi-ts — drf-spectacular emits ordering
    // patterns like ``(?:id|\-id)`` where the ``\-`` outside a character
    // class is technically unnecessary but harmless. ``no-useless-escape``
    // isn't auto-fixable, so relax it only for the generated folder.
    files: ['shared/openapi/**/*.ts'],
    rules: {
      'no-useless-escape': 'off',
      '@typescript-eslint/no-invalid-void-type': 'off',
    },
  },
  {
    // Mechanical guard for the project rule "never import from
    // ``#shared/...`` in app/ or server/" — see ~/.claude/projects/
    // .../memory/feedback_no_shared_imports.md.
    //
    // Everything under ``shared/`` is auto-imported by Nuxt's
    // ``imports.dirs: ['../shared/**']``. Explicit imports cause Vite
    // "Duplicated imports" warnings, break the test runtime resolver,
    // and routinely creep back in. Catch them at the lint step.
    //
    // Scope: app/** + server/**. ``shared/`` itself is allowed to
    // re-export internally; ``test/`` keeps explicit imports because
    // vitest's resolver doesn't honour Nuxt auto-imports.
    files: ['app/**/*.{ts,vue}', 'server/**/*.{ts,vue}'],
    rules: {
      // ``no-restricted-imports`` (the core rule) skips ``import
      // type`` by default, which is exactly the form that's been
      // sneaking back in. The typescript-eslint variant checks
      // both forms — keep both rules on so a pure JS file (rare)
      // is still caught.
      'no-restricted-imports': ['error', {
        patterns: [
          {
            // Regex form — glob patterns ('#shared/*', '#shared/**')
            // didn't match consistently across the eslint+nuxt
            // resolver chain. ``^#shared(/|$)`` reliably catches
            // both ``import '#shared'`` and any subpath.
            regex: '^#shared(/|$)',
            message:
              'Auto-imported. Drop the explicit import — Nuxt picks '
              + 'up everything under shared/ via imports.dirs. '
              + 'See feedback_no_shared_imports.md.',
          },
        ],
      }],
      '@typescript-eslint/no-restricted-imports': ['error', {
        patterns: [
          {
            // Regex form — glob patterns ('#shared/*', '#shared/**')
            // didn't match consistently across the eslint+nuxt
            // resolver chain. ``^#shared(/|$)`` reliably catches
            // both ``import '#shared'`` and any subpath.
            regex: '^#shared(/|$)',
            message:
              'Auto-imported. Drop the explicit import — Nuxt picks '
              + 'up everything under shared/ via imports.dirs. '
              + 'See feedback_no_shared_imports.md.',
          },
        ],
      }],
    },
  },
  {
    // One set of fetchers for the storefront's own `/api`: `$api`,
    // `useApi`, `useLazyApi`, `useRequestApi` (app/utils/api.ts,
    // app/composables/useApi.ts). They state the PAGE's locale on every
    // request (`pageLocaleHeader`), which is how Django answers in the
    // language the visitor is reading and how the Nitro caches key on
    // it. A raw `$fetch` / `useFetch` / `useLazyFetch` /
    // `useRequestFetch` sends no locale, so the server would answer in
    // the default language — and cache that answer for everyone.
    //
    // `$fetch` is deliberately not globally configurable (Nuxt 4 "Custom
    // useFetch" recipe), so this cannot be fixed underneath the call
    // sites; it has to be kept out of them. The plugin that builds the
    // instance and the composables that wrap Nuxt's fetchers are the
    // only places allowed to touch them.
    files: ['server/**/*.ts'],
    rules: {
      'no-restricted-syntax': ['error', ...RETURN_AWAITED_IN_TRY],
    },
  },
  {
    files: ['app/**/*.{ts,vue}'],
    ignores: ['app/plugins/api.ts', 'app/composables/useApi.ts'],
    rules: {
      'no-restricted-syntax': ['error', ...APP_FETCHER_SELECTORS, PAGE_CONFIG_AWAITED],
    },
  },
  {
    // Repeats the app-wide selectors — see APP_FETCHER_SELECTORS for why.
    files: ['app/components/**/*.vue'],
    rules: {
      'no-restricted-syntax': ['error', ...APP_FETCHER_SELECTORS, PAGE_CONFIG_AWAITED, NO_PAGE_MACROS],
    },
  },
  {
    // Reka's `useForwardExpose` checks that `$el` exists as a KEY, never
    // that it is non-null; a `Lazy*` component renders nothing until its
    // chunk arrives, so `$el` is null in that window and it throws
    // "Cannot read properties of null (reading 'nodeName')". Measured on
    // staging 2026-09-21: `/account/sessions` threw it once per table
    // row and hydrated with mismatches. The lazy wrapper bought nothing —
    // `Page/Navbar.vue` renders `UDropdownMenu` eagerly on every page.
    files: ['app/**/*.vue'],
    rules: {
      'vue/no-restricted-html-elements': ['error', {
        element: ['LazyUDropdownMenu', 'lazy-u-dropdown-menu'],
        message: 'Use <UDropdownMenu>: Reka\'s useForwardExpose throws on the null $el of a lazy component.',
      }],
    },
  },
  {
    rules: {
      ...eslintPluginBetterTailwindcss.configs['recommended-warn'].rules,
      'better-tailwindcss/no-unknown-classes': ['warn', {
        detectComponentClasses: true,
        ignore: [
          'article',
          // NuxtUI
          'text-elevated*',
          'bg-elevated*',
          'border-elevated*',
          'ring-elevated*',
          'text-default*',
          'bg-default*',
          'border-default*',
          'ring-default*',
          'text-primary*',
          'bg-primary*',
          'border-primary*',
          'ring-primary*',
          'text-secondary*',
          'bg-secondary*',
          'border-secondary*',
          'ring-secondary*',
        ],
      }],
      'nuxt/prefer-import-meta': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-multiple-template-root': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/no-v-html': 'off',
      'vue/no-watch-after-await': 'warn',
      'vue/no-lifecycle-after-await': 'warn',
      'vue/attribute-hyphenation': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-console': 'error',
    },
  },
  {
    // Tests are code. Until 2026-09-30 `test/` sat in the global ignores,
    // and nothing flagged 26 spec files that asserted on their own
    // literals, a stale import of a deleted function, or unused imports.
    // The vitest plugin's recommended set catches the test-shaped
    // mistakes (focused/disabled tests, tests with no assertion,
    // conditional or standalone `expect`, identical titles); the rest keep
    // hooks where a reader looks for them.
    files: ['test/**/*.ts'],
    plugins: { vitest },
    rules: {
      ...vitest.configs.recommended.rules,
      // Vitest runs only `*.spec.ts` (vitest.config.mts), so a
      // `*.test.ts` file is silently never run — that is how six such
      // files once went uncounted. Suite modules that a spec imports
      // (`test/e2e/pageRenders.ts`) match neither pattern and are fine.
      'vitest/consistent-test-filename': ['error', {
        pattern: String.raw`.*\.spec\.ts$`,
        allTestPattern: String.raw`.*\.(test|spec)\.[cm]?[jt]sx?$`,
      }],
      'vitest/prefer-hooks-on-top': 'error',
      'vitest/no-duplicate-hooks': 'error',
      // Vitest's signature is `expect(actual, message?)`; the rule's
      // default of one argument only lets a LITERAL message through, and
      // flags a computed one (`expect(x, \`${slot} …\`)` passes, a
      // concatenated or variable message does not) — the same valid API.
      'vitest/valid-expect': ['error', { maxArgs: 2 }],
      // An assertion helper is named `expect…` (`expectLastQuery`,
      // `expectSnapshot`, `expectFailure`): the test that calls one does
      // assert, and a helper that asserts is findable by its name.
      'vitest/expect-expect': ['error', { assertFunctionNames: ['expect', 'expect*'] }],
    },
  },
  {
    // A CLI script REPORTS to stdout — that is what it is for, so
    // `no-console` there only buys a disable comment per line (the
    // two older scripts each carry several). Scoped to `scripts/`, so
    // nothing shipped to a browser is covered.
    files: ['scripts/**/*.{js,mjs,ts}'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    settings: {
      'better-tailwindcss': {
        entryPoint: 'app/assets/css/main.css',
        variables: [],
        attributes: [
          ['^v-bind:ui$', [
            { match: 'objectValues' },
          ]],
          ['^(?:v-bind:)?(activeClass|inactiveClass)$', [
            { match: 'strings' },
            { match: 'objectKeys' },
            { match: 'objectValues' },
          ]],
        ],
      },
    },
  },
)
