import eslintPluginBetterTailwindcss from 'eslint-plugin-better-tailwindcss'
// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'
import { globalIgnores } from 'eslint/config'

export default withNuxt(
  globalIgnores([
    '**/test/',
    // Only ignore the raw schema files at the project root, NOT the
    // generated TS/Zod sources in ``shared/openapi/`` — otherwise the
    // openapi-ts ESLint post-processor fails with "all matching files
    // are ignored" and the codegen crashes mid-run.
    'openapi/**',
    '**/.nuxt/**',
    '**/.output/**',
    '**/dist/**',
    '**/build/**',
    '**/node_modules/**',
    '**/.pnpm-store/**',
    '**/.cache/**',
    '**/.eslintcache',
    '**/coverage/**',
    '**/*.log',
    '**/*.md',
    '**/logs/**',
    '**/skills/**',
  ]),
  {
    plugins: {
      'better-tailwindcss': eslintPluginBetterTailwindcss,
    },
  },
  {
    // Generated by @hey-api/openapi-ts — drf-spectacular emits ordering
    // patterns like ``(?:id|\-id)`` where the ``\-`` outside a character
    // class is technically unnecessary but harmless. ``no-useless-escape``
    // isn't auto-fixable, so relax it only for the generated folder.
    files: ['shared/openapi/**/*.ts'],
    rules: {
      'no-useless-escape': 'off',
      '@typescript-eslint/no-invalid-void-type': 'off',
    },
  },
  {
    // Mechanical guard for the project rule "never import from
    // ``#shared/...`` in app/ or server/" — see ~/.claude/projects/
    // .../memory/feedback_no_shared_imports.md.
    //
    // Everything under ``shared/`` is auto-imported by Nuxt's
    // ``imports.dirs: ['../shared/**']``. Explicit imports cause Vite
    // "Duplicated imports" warnings, break the test runtime resolver,
    // and routinely creep back in. Catch them at the lint step.
    //
    // Scope: app/** + server/**. ``shared/`` itself is allowed to
    // re-export internally; ``test/`` keeps explicit imports because
    // vitest's resolver doesn't honour Nuxt auto-imports.
    files: ['app/**/*.{ts,vue}', 'server/**/*.{ts,vue}'],
    rules: {
      // ``no-restricted-imports`` (the core rule) skips ``import
      // type`` by default, which is exactly the form that's been
      // sneaking back in. The typescript-eslint variant checks
      // both forms — keep both rules on so a pure JS file (rare)
      // is still caught.
      'no-restricted-imports': ['error', {
        patterns: [
          {
            // Regex form — glob patterns ('#shared/*', '#shared/**')
            // didn't match consistently across the eslint+nuxt
            // resolver chain. ``^#shared(/|$)`` reliably catches
            // both ``import '#shared'`` and any subpath.
            regex: '^#shared(/|$)',
            message:
              'Auto-imported. Drop the explicit import — Nuxt picks '
              + 'up everything under shared/ via imports.dirs. '
              + 'See feedback_no_shared_imports.md.',
          },
        ],
      }],
      '@typescript-eslint/no-restricted-imports': ['error', {
        patterns: [
          {
            // Regex form — glob patterns ('#shared/*', '#shared/**')
            // didn't match consistently across the eslint+nuxt
            // resolver chain. ``^#shared(/|$)`` reliably catches
            // both ``import '#shared'`` and any subpath.
            regex: '^#shared(/|$)',
            message:
              'Auto-imported. Drop the explicit import — Nuxt picks '
              + 'up everything under shared/ via imports.dirs. '
              + 'See feedback_no_shared_imports.md.',
          },
        ],
      }],
    },
  },
  {
    rules: {
      ...eslintPluginBetterTailwindcss.configs['recommended-warn'].rules,
      'better-tailwindcss/no-unknown-classes': ['warn', {
        detectComponentClasses: true,
        ignore: [
          'article',
          // NuxtUI
          'text-elevated*',
          'bg-elevated*',
          'border-elevated*',
          'ring-elevated*',
          'text-default*',
          'bg-default*',
          'border-default*',
          'ring-default*',
          'text-primary*',
          'bg-primary*',
          'border-primary*',
          'ring-primary*',
          'text-secondary*',
          'bg-secondary*',
          'border-secondary*',
          'ring-secondary*',
        ],
      }],
      'nuxt/prefer-import-meta': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-multiple-template-root': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/no-v-html': 'off',
      'vue/no-watch-after-await': 'warn',
      'vue/no-lifecycle-after-await': 'warn',
      'vue/attribute-hyphenation': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-console': 'error',
    },
  },
  {
    settings: {
      'better-tailwindcss': {
        entryPoint: 'app/assets/css/main.css',
        variables: [],
        attributes: [
          ['^v-bind:ui$', [
            { match: 'objectValues' },
          ]],
          ['^(?:v-bind:)?(activeClass|inactiveClass)$', [
            { match: 'strings' },
            { match: 'objectKeys' },
            { match: 'objectValues' },
          ]],
        ],
      },
    },
  },
)
