services:
  storefront_uinode_nuxt:
    container_name: storefront_uinode_nuxt
    restart: no
    image: gro0ve/grooveshop-storefront-ui-node-nuxt:latest
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    networks:
      - groovy-backbone

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - groovy-backbone

networks:
  groovy-backbone:
    driver: bridge
