/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IconAntDesign:tikTokFilled': typeof import('~icons/ant-design/tik-tok-filled')['default']
    'IconFa6Solid:cartShopping': typeof import('~icons/fa6-solid/cart-shopping')['default']
    'IconFa6Solid:circleUser': typeof import('~icons/fa6-solid/circle-user')['default']
    'IconFa6Solid:magnifyingGlass': typeof import('~icons/fa6-solid/magnifying-glass')['default']
    'IconFaSolid:angleLeft': typeof import('~icons/fa-solid/angle-left')['default']
    'IconFaSolid:angleRight': typeof import('~icons/fa-solid/angle-right')['default']
    'IconMdi:facebook': typeof import('~icons/mdi/facebook')['default']
    'IconMdi:instagram': typeof import('~icons/mdi/instagram')['default']
    'IconMdi:pinterest': typeof import('~icons/mdi/pinterest')['default']
    'IconMdi:reddit': typeof import('~icons/mdi/reddit')['default']
    'IconMdi:youtube': typeof import('~icons/mdi/youtube')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
