/**
 * Stamps the per-request CSP nonce (generated by
 * ``server/middleware/3.csp.ts``) onto every SSR-emitted ``<script>`` and
 * script-preload ``<link>`` tag, per the Nuxt-documented pattern. The
 * streaming renderer reuses the nonce it finds on head scripts for its own
 * internal inline scripts, so stamping head + body chunks is sufficient.
 *
 * No-ops when the middleware set no nonce (dev, prerender passes, and the
 * prerendered static pages, which keep the 'unsafe-inline' policy).
 */
export default defineNitroPlugin((nitro) => {
  nitro.hooks.hook('render:html', (html, { event }) => {
    const nonce = event.context.cspNonce as string | undefined
    if (!nonce) {
      return
    }
    // ``body`` is included because unhead renders bodyClose tags (e.g.
    // nuxt-site-config's inline ``window.__NUXT_SITE_CONFIG__`` script)
    // into the app-body chunk, not bodyAppend. Stamping body scripts
    // grants nothing beyond the legacy 'unsafe-inline' fallback already
    // in the policy — but skipping it CSP-blocks those legit scripts.
    for (const key of ['head', 'body', 'bodyPrepend', 'bodyAppend'] as const) {
      html[key] = html[key].map(chunk => stampCspNonce(chunk, nonce))
    }
  })
})
